stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update -qy  # Update package list (for Ubuntu-based runners)
  - apt-get install -y nodejs npm  # Install Node.js and npm
  - node -v  # Print Node.js version for verification
  - npm -v   # Print npm version for verification


build-job:
  stage: build
  script:
    - echo "Bắt đầu quá trình xây dựng..."
    - cd back-end-docker          # Di chuyển vào thư mục "backend"    
    - npm install         # Cài đặt các module trong thư mục "backend"
    - npm install express
    - echo "Cài đặt hoàn thành."
    - echo "Biên dịch TypeScript (nếu có)..."    
    - echo "Biên dịch hoàn thành."
    - echo "Chuẩn bị tài liệu hoặc các tác vụ khác ở đây..."
    - echo "Xây dựng hoàn thành."

test-job:
  stage: test
  script:
    - echo "Bắt đầu quá trình kiểm tra..."    
    - cd back-end-docker  # Di chuyển vào thư mục "backend"    
    - npm install
    - npx mocha test
    # Thêm các lệnh kiểm tra ở đây
    - echo "Kiểm tra hoàn thành."

deploy-job:
  stage: deploy
  script:
    - echo "Bắt đầu quá trình triển khai..."
    - cd back-end-docker  # Navigate to the backend directory (assuming backend is the backend folder)
    - npm install  # Install backend dependencies
    # Optionally, you can include the following to display the deployment URL
    - echo "Ứng dụng đã được triển khai tại"
    - echo "Triển khai hoàn thành."

